spring.application.name=main
# Show error message
spring.web.error.include-message=always

# Show exception details
spring.web.error.include-exception=true

# Show stack trace
spring.web.error.include-stacktrace=always

# Show binding/validation errors
spring.web.error.include-binding-errors=always