spring.application.name=main
# Show error message
spring.web.error.include-message=always

# Show exception details
spring.web.error.include-exception=true

# Show stack trace
spring.web.error.include-stacktrace=always

# Show binding/validation errors
spring.web.error.include-binding-errors=always
spring.datasource.url=jdbc:mysql://localhost:3306/mediblock
spring.datasource.username=root
spring.datasource.password=Subi@14082006
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
